"""
constants for Texas Department of State Health Services Regions

source: https://hhs.texas.gov/sites/default/files/documents/about-hhs/hhs-regional-map.pdf
reference: https://dshs.texas.gov/regions/default.shtm
"""
region1 = [
    "Armstrong",
    "Bailey",
    "Briscoe",
    "Carson",
    "Castro",
    "Childress",
    "Cochran",
    "Collingsworth",
    "Crosby",
    "Dallam",
    "Deaf Smith",
    "Dickens",
    "Donley",
    "Floyd",
    "Garza",
    "Gray",
    "Hale",
    "Hall",
    "Hansford",
    "Hartley",
    "Hemphill",
    "Hockley",
    "Hutchinson",
    "King",
    "Lamb",
    "Lipscomb",
    "Lubbock",
    "Lynn",
    "Moore",
    "Motley",
    "Ochiltree",
    "Oldham",
    "Parmer",
    "Potter",
    "Randall",
    "Roberts",
    "Sherman",
    "Swisher",
    "Terry",
    "Wheeler",
    "Yoakum",
]

region2 = [
    "Archer",
    "Baylor",
    "Brown",
    "Callahan",
    "Clay",
    "Coleman",
    "Comanche",
    "Cottle",
    "Eastland",
    "Fisher",
    "Foard",
    "Hardeman",
    "Haskell",
    "Jack",
    "Jones",
    "Kent",
    "Knox",
    "Mitchell",
    "Montague",
    "Nolan",
    "Runnels",
    "Scurry",
    "Shackelford",
    "Stephens",
    "Stonewall",
    "Taylor",
    "Throckmorton",
    "Wichita",
    "Wilbarger",
    "Young",
]

region3 = [
    "Collin",
    "Cooke",
    "Dallas",
    "Denton",
    "Ellis",
    "Erath",
    "Fannin",
    "Grayson",
    "Hood",
    "Hunt",
    "Johnson",
    "Kaufman",
    "Navarro",
    "Palo",
    "Pinto",
    "Parker",
    "Rockwall",
    "Somervell",
    "Tarrant",
    "Wise",
]

region4 = [
    "Anderson",
    "Bowie",
    "Camp",
    "Cass",
    "Cherokee",
    "Delta",
    "Franklin",
    "Gregg",
    "Harrison",
    "Henderson",
    "Hopkins",
    "Lamar",
    "Marion",
    "Morris",
    "Panola",
    "Rains",
    "Red",
    "River",
    "Rusk",
    "Smith",
    "Titus",
    "Upshur",
    "Van Zandt",
    "Wood",
]

region5 = [
    "Angelina",
    "Hardin",
    "Houston",
    "Jasper",
    "Jefferson",
    "Nacogdoches",
    "Newton",
    "Orange",
    "Polk",
    "Sabine",
    "San Augustine",
    "San Jacinto",
    "Shelby",
    "Trinity",
    "Tyler",
]

region6 = [
    "Austin",
    "Brazoria",
    "Chambers",
    "Colorado",
    "Fort Bend",
    "Galveston",
    "Harris",
    "Liberty",
    "Matagorda",
    "Montgomery",
    "Walker",
    "Waller",
    "Wharton",
]

region7 = [
    "Bastrop",
    "Bell",
    "Blanco",
    "Bosque",
    "Brazos",
    "Burleson",
    "Burnet",
    "Caldwell",
    "Coryell",
    "Falls",
    "Fayette",
    "Freestone",
    "Grimes",
    "Hamilton",
    "Hays",
    "Hill",
    "Lampasas",
    "Lee",
    "Leon",
    "Limestone",
    "Llano",
    "Madison",
    "McLennan",
    "Milam",
    "Mills",
    "Robertson",
    "San Saba",
    "Travis",
    "Washington",
    "Williamson",
]

region8 = [
    "Atascosa",
    "Bandera",
    "Bexar",
    "Calhoun",
    "Comal",
    "DeWitt",
    "Dimmit",
    "Edwards",
    "Frio",
    "Gillespie",
    "Goliad",
    "Gonzales",
    "Guadalupe",
    "Jackson",
    "Karnes",
    "Kendall",
    "Kerr",
    "Kinney",
    "LaSalle",
    "Lavaca",
    "Maverick",
    "Medina",
    "Real",
    "Uvalde",
    "Val Verde",
    "Victoria",
    "Wilson",
    "Zavala",
]


region9 = [
    "Andrews",
    "Borden",
    "Coke",
    "Concho",
    "Crane",
    "Crockett",
    "Dawson",
    "Ector",
    "Gaines",
    "Glasscock",
    "Howard",
    "Irion",
    "Kimble",
    "Loving",
    "Martin",
    "Mason",
    "McCulloch",
    "Menard",
    "Midland",
    "Pecos",
    "Reagan",
    "Reeves",
    "Schleicher",
    "Sterling",
    "Sutton",
    "Terrell",
    "Tom Green",
    "Upton",
    "Ward",
    "Winkler",
]


region10 = ["Brewster" "Culberson" "El Paso" "Hudspeth" "Jeff" "Davis" "Presidio"]


region11 = [
    "Aransas",
    "Bee",
    "Brooks",
    "Cameron",
    "Duval",
    "Hidalgo",
    "Jim Hogg",
    "Jim Wells",
    "Kenedy",
    "Kleberg",
    "Live",
    "Oak",
    "McMullen",
    "Nueces",
    "Refugio",
    "San Patricio",
    "Starr",
    "Webb",
    "Willacy",
    "Zapata",
]
